alaphang/urls.py
from django.contrib import admin
from django.urls import path, include

# summernote
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
    
]

# summernote
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    
    #path('<int:post_order>/', views.DetailView, name='detail'),#
    path('page/<slug:slug>/', views.PageDetailView.as_view(), name='page'),
    path('category/<slug:slug>/', views.Categorys.as_view(), name='categorys'),
    path('<slug:slug>/', views.SlugDetailView.as_view(), name='detail'),
    path('', views.IndexView.as_view(), name='index'),
]

blog/models.py
from django.db import models

def defaultOrder():
    if Post.objects.all():
        return  Post.objects.order_by('-post_order')[0].post_order+1
    else:
        return 1

class Category(models.Model):
    category_name = models.CharField(max_length=200)
    slug = models.SlugField()
    category_order = models.PositiveSmallIntegerField()

    def __str__(self):
        return self.category_name

    class Meta:
        ordering = ["category_order"]

class Post(models.Model):
    post_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    post_title = models.CharField(max_length=200)
    post_content = models.TextField()
    post_published = models.BooleanField(default=True)    
    post_order = models.PositiveSmallIntegerField(default=defaultOrder)
    slug = models.SlugField()

    def __str__(self):
        return self.post_title

    class Meta:
        ordering = ["post_order"]

class Page(models.Model):
    page_title = models.CharField(max_length = 200)
    page_content = models.TextField()
    slug = models.SlugField()
    page_order = models.PositiveSmallIntegerField()
    page_show_in_navbar= models.BooleanField(default=True)

    def __str__(self):
        return self.page_title

    class Meta:
        ordering = ["page_order"]

blog/views.py
from django.shortcuts import get_object_or_404, render

from .models import Post, Category, Page

from django.views import View
from django.views import generic

def getPostNumber():
    postnumbers = {}
    for category in Category.objects.all():
        postnumbers[category.slug] = (Post.objects.filter(post_category=category).count())
    return postnumbers

def DetailView(request, post_order):
    post = get_object_or_404(Post, post_order=post_order)
    posts = Post.objects.all()
    navbars = Post.objects.filter(post_show_in_navbar = True)
    categorys = Category.objects.all()
    posts_in_category = Post.objects.filter(post_category = post.post_category)
    context = {
        'post': post,
        'posts': posts,
        'navbars': navbars,
        'categorys': categorys,
        'posts_in_category': posts_in_category
    }
    return render(request, 'blog/detail.html', context)


class SlugDetailView(generic.DetailView):
    model = Post
    template_name = 'blog/detail.html'

    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)
           
            if Post.objects.filter(post_order = self.object.post_order+1).exists():
                context['next'] = Post.objects.get(post_order=self.object.post_order+1)
            else:
                context['next'] = None

            if Post.objects.filter(post_order = self.object.post_order-1).exists():
                context['prev'] = Post.objects.get(post_order=self.object.post_order-1)
            else:
                context['prev'] = None

            context['categorys'] = Category.objects.all()
            context['posts_in_actual_category'] = Post.objects.filter(post_category=self.object.post_category)
            context['navbars'] = Page.objects.all()
            context['title'] = self.object.post_title    
            return context

class PageDetailView(generic.DetailView):
    model = Page
    template_name = 'blog/page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navbars'] = Page.objects.all()
        context['title'] = self.object.page_title 
        context['categorys'] = Category.objects.all()
        return context


class Categorys(generic.ListView):
    model = Category
    template_name ='blog/category_list.html'
    
    def get_context_data(self, **kwargs):
            context = super().get_context_data(**kwargs)           
            context['categorys'] = Category.objects.all()
            context['navbars'] = Page.objects.all()
            context['posts'] = Post.objects.all()
            context['postnumbers'] = getPostNumber
            context['title'] = 'Kategóriák - Alaphang'
            return context
            

class Posts(generic.ListView):
    model = Post

class IndexView(generic.TemplateView):
    template_name = "blog/index.html"
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['navbars'] = Page.objects.all()
        context['firstpost'] = Post.objects.all()[:1].get()
        context['title'] = 'Alaphang' 
        context['categorys'] = Category.objects.all()
        return context

templates/blog/base.html
<!DOCTYPE html>
<html lang="hu">
<head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-15526777-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-15526777-1');
</script>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'clean-blog.css' %}">

<title>{{ title }}</title>
</head>
<body>

{% include "blog/navbar.html" %}

 <div class="container">  
        <div class="row">        
        {% include "blog/sidebar.html" %}
        {% block content %}{% endblock %}
        {% block page_content %}{% endblock %}   
        {% block category %}{% endblock %} 
        
        </div>
</div> 

{% include "blog/footer.html" %}
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>   
</body>
</html>

templates/blog/category_list.html
{% extends "blog/base.html" %}

{% block category %}
<div class="col-sm">   

        <ul class="list-group">
          {% for category in categorys %}
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <a class="text-muted d-block"  data-toggle="collapse" href="#{{category.slug}}" role="button">{{ category.category_name }}</a> 
            <span class="badge badge-primary badge-pill">
              {% for key, value in postnumbers.items %}
              {% if key == category.slug%}
              {{ value}}
              {%endif%}        
              {% endfor %}
            </span>       
          </li>
          

          <div id="{{category.slug}}" class="collapse">
            <ul class="list-group">
              {% for post in posts %}
              {% if post.post_category.pk == category.pk %}
              <li class="list-group-item d-flex justify-content-between align-items-center">
              <a href="{% url 'blog:detail' post.slug %}">{{ post.post_title}}</a>    
              </li>
              {%endif%}   
              {% endfor %}
            </ul>
        </div>

          {% endfor %} 
          </ul>


              
</div>
{% endblock %}

templates/blog/detail.html
{% extends "blog/base.html" %}

{% block content %}

<div class="col-sm-12 col-md-9">
  {% if post %}
  <div class="card border-light mb-3">
    <div class="card-header bg-success text-center">

      {% if next  %}
      <a class="btn btn-success" href="{% url 'blog:detail' next.slug %}">Következő:
        {{next.post_title}}</a>
      {% endif %}

      {% if prev  %}
      <a class="btn btn-success" href="{% url 'blog:detail' prev.slug %}">Előző: {{prev.post_title}}</a>
      {% endif %}
    </div>
    <div class="card-body">
      <h2 class="card-title ">{{ post.post_title }} </h2>
      <p class="content">{{ post.post_content | safe }}</p>
    </div>


    <div class="card-header bg-success text-center">

      {% if next  %}
      <a class="btn btn-success" href="{% url 'blog:detail' next.slug %}">Következő:
        {{next.post_title}}</a>
      {% endif %}

      {% if prev  %}
      <a class="btn btn-success" href="{% url 'blog:detail' prev.slug %}">Előző: {{prev.post_title}}</a>
      {% endif %}
    </div>

  </div>

  {% else %}
  <p>Nincs ilyen cikk.</p>
  {% endif %}

</div>

{% endblock %}

templates/blog/footer.html
<div class="container-fluid bg-dark text-white mt-2">
    <div class="container p-5">
    <div class="row">
        <div class="col">
            {% if navbars %}  
            {% for navbar in navbars %}
            <a class="p-2 text-muted d-inline-block" href="{% url 'blog:page' navbar.slug %}">{{ navbar.page_title }}</a>
            {% endfor %}
            {% else %}
            <p>Nincs ilyen cikk.</p>
          {% endif %}   
</div>
</div>
</div>
</div>

templates/blog/index.html
{% extends "blog/base.html" %}

{% block category %}
<div class="col-sm-12 col-md-9">

    <div class="jumbotron">
        <h1 class="display-4">Alaphang </h1>
        <p class="lead">Alaphang - mert valahol el kell kezdeni!</p>
        <hr class="my-4">
    <p>Kinek szól ez a weboldal?</p>
<p> Mindenkinek, aki szeretne megtanulni gitározni. Kezdőknek, újrakezdőknek, gyerekeknek, felnőtteknek.
        A weboldal segítségével megszerezheted az alapvető elméleti és gyakorlati ismereteket a gitározással kapcsolatban.</p>
        
    <p>Mit tanulhatok meg?</p>
<p> Megismerheted a gitárt, mint hangszert, felépítését, történelmét. Külön rész foglalkozik az elektromos gitárokkal.
     Megtanulhatod a legfontosabb akkordokat, képes leszel dalkíséret eljátszására. Megismerkedhetsz a szólózás alapjaival, a skálákkal, a szólózási technikákkal.</p>
        
    <p>Hogyan használjam?</p>
</p>Az oldalt egyrészt lehet tankönyvszerűen használni, tehát fejezetről fejezetre haladhatsz.
Másrészt bizonyos részeket akár önállóan is tanulmányozhatsz, illetve visszatérhetsz feleleveníteni egy adott fejezetet.</p>
        
<p>Hogyan épül fel a weboldal?</p>
<p> Az első rész a gitárról szóló elméleti bevezető. Aztán következik egy nem túl hosszú, de roppant fontos zeneelméleti rész, ide többször visszatérhetsz olvasgatni. 
    Ezután megismerheted a legfontosabb akkordokat és dalkíséreti lehetőségeket.
        A szólótechnika a skálák megismerésén és megértésén alapul, az oldalnak ez a része részletesen foglalkozik a skálák lejátszásával a gitáron.</p>
        
    <p class="alert alert-warning">A gitártanulás kitartást igényel, ez a legfontosabb. Ne add fel túl korán, és az eredmények jönni fognak! </p>
        
        <a class="btn btn-primary btn-lg" href="{% url 'blog:detail' firstpost.slug %}" role="button">Kezdj is bele!</a>
      </div>




</div>
{% endblock %}

templates/blog/navbar.html
<div class="container">
    <div class="row">
        <div class="col">
            <div class="navbar-light">
              <div class="navbar-light">
                <p class="navbar-toggler d-md-none btn d-block mb-1 text-left"  data-toggle="collapse" data-target="#collapseNavbar" aria-controls="collapseNavbar" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span> Menü
                </p>
                </div>
                  
            <div class="py-1 mb-2 collapse d-md-block" id="collapseNavbar">

                <nav class="nav d-flex flex-column flex-md-row justify-content-md-between   border-bottom border-dark" >
                    <a class="p-2 text-muted" href="{% url 'blog:index' %}">Alaphang</a>

                  {% if navbars %}  
                    {% for navbar in navbars %}
                    <a class="p-2 text-muted" href="{% url 'blog:page' navbar.slug %}">{{ navbar.page_title }}</a>
                    {% endfor %}
                    {% else %}
                    <p>Nincs ilyen cikk.</p>
                  {% endif %}    

                </nav>
              </div>

           </div> 
        </div>
    </div>
</div>

templates/blog/page.html
{% extends "blog/base.html" %}

{% block page_content %}
<div class="col-sm-12 col-md-9">

       
        {{ page.page_content|safe }}
        

   </div> 
  {% endblock %}
  
  
  
    

templates/blog/sidebar.html
<div class="col-sm-12 col-md-3">
  


  <div class="navbar-light">
    <p class="navbar-toggler d-md-none btn btn-primary d-block mb-1 text-left" data-toggle="collapse"
      data-target="#collapseSidebar" aria-controls="collapseSidebar" aria-expanded="false"
      aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span> Tartalom
    </p>
  </div>

  <div class="collapse d-md-block" id="collapseSidebar">
    
    <div class="card mb-5">
      <h5 class="card-header">Kategóriák</h5>
      <div class="card-body">
        <!-- <h6 class="card-title border-bottom">{{ post.post_category  }}</h5> -->
        {% if categorys %}
          {% for category in categorys %}
            {% if category.pk == post.post_category.pk %}
            <a href="{% url 'blog:categorys' category.slug %}"
              class="btn btn-danger d-block mb-1">{{ category.category_name }}</a>
            {% else %}
            <a href="{% url 'blog:categorys' category.slug %}"
              class="btn btn-primary d-block mb-1">{{ category.category_name }}</a>
            {% endif %}
          {% endfor %}
        {% endif %}
      </div>
    </div>
   
    {% if post %}
    <div class="card mb-5">
      <div class="card-body">

        {% if next  %}
        <a class="btn btn-primary d-block mb-1" href="{% url 'blog:detail' next.slug %}">Következő:
          {{next.post_title}}</a>
        {% endif %}

        {% if prev  %}
        <a class="btn btn-primary d-block mb-1" href="{% url 'blog:detail' prev.slug %}">Előző: {{prev.post_title}}</a>
        {% endif %}

      </div>
    </div>


    <div class="card mb-5">
      <h5 class="card-header">Továbbiak</h5>
      <div class="card-body">
        <p class="card-text"><i>{{ post.post_category  }}</i> kategőria többi cikke:</p>
      </div>

      {% for post_in_actual_category in posts_in_actual_category %}
      <ul class="list-group list-group-flush">
        {% if post_in_actual_category.pk == post.pk %}
        <li class="list-group-item">
          <a class=" text-secondary"
            href="{% url 'blog:detail' post_in_actual_category.slug %}">{{ post_in_actual_category.post_title }}</a>
        </li>
        {% else %}
        <li class="list-group-item">
          <a class="text-primary"
            href="{% url 'blog:detail' post_in_actual_category.slug %}">{{ post_in_actual_category.post_title }}</a>
        </li>
        {%endif%}
        {% endfor %}
      </ul>
    </div>


{% endif %}
  </div>
</div> 